(:name           "gromacs")
(:repo           "taffish-org/gromacs")
(:author         "KaiyuanHan")
(:version        "2025.1")
(:intro          "A free and open-source software suite for high-performance molecular dynamics and output analysis.")
(:dependencies)
(:functions      "gmx")
